# Generated by Django 4.0.4 on 2022-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_requestbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='date_of_request',
            field=models.DateField(auto_now=True),
        ),
    ]
