# Generated by Django 4.0.4 on 2022-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_requestbook_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
