# Generated by Django 4.0.4 on 2022-05-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
